mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: media # URL where the media files are served from.

plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - myplugin.MyPlugin
context:
    data:
        site_title: Binstar Documentation
        author:
            name: Continuum Analytics
            url: "https://binstar.org/"
        #google_analytics_id: UA-40918310-2
        home_url: index.html
        menu:
            - title: Getting Started
              url : 'index.html'
            - title : Frequently Asked Questions
              url : 'faq.html'
            - title : Conda Packaging
              url : "conda.html"
            - title : PyPI Packaging
              url : "pypi.html"
            - title : Token Generation
              url : "token_gen.html"

simple_copy:
    - media/js/*
    - media/js/libs*
    - media/css/*
