mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
base_url: /

plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - command_line_plugin.CommandLinePlugin

context:
    data:
        repo: https://github.com/Anaconda-Server/docs.anaconda.org
        branch: master
        imports:
          - binstar
        site_title: anaconda.org documentation
        author:
            name: Continuum Analytics
            url: "https://anaconda.org/"
        home_url: index.html
        brand: Anaconda Cloud docs
        pages:
          - name: Using Anaconda Cloud
            url: using.html
            id: using
          - name: Building Packages
            url: building.html
            id: building
          - name: Build Reference
            url: build-config.html
            id: build-config
          - name: Command Reference
            url: cli.html
            id: cli
          - name: FAQ
            url: faq.html
            id: faq
          - name: OnSite
            url: http://docs.continuum.io/anaconda-server/index.html
            id: null

simple_copy:
    - media/js/*
    - media/js/libs*
    - media/css/*
