mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /static/docs/media # URL where the media files are served from.
base_url: /static/docs

plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - command_line_plugin.CommandLinePlugin

context:
    data:
        repo: https://github.com/Anaconda-Server/docs.anaconda.org
        branch: master
        imports:
          - binstar
        site_title: Anaconda Repository Documentation
        author:
            name: Continuum Analytics
            url: "https://anaconda.org/"
        home_url: index.html
        brand: Anaconda Repository
        pages:
          - name: Quickstart
            url: quickstart.html
            id: quickstart
          - name: Account Management
            url: managing-account.html
            id: managing-account
          - name: Anaconda Repository
            url: using.html
            id: using
          - name: Anaconda Build
            url: build.html
            id: build
          - name: Reference
            url: reference.html
            id: reference
          - name: Command Reference
            url: cli.html
            id: cli

simple_copy:
    - media/js/*
    - media/js/libs*
    - media/css/*
