mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: media # URL where the media files are served from.

plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
context:
    data:
        site_title: Binstar Documentation
        author:
            name: Continuum Analytics
            url: "https://binstar.org/"
        #google_analytics_id: UA-40918310-2
        home_url: gettingstarted.html
        menu:
            - title: Getting Started
              submenu :
                - title : What Is Binstar?
                  url : index.html
                - title : What Can You Do With Binstar?
                  url : gettingstarted.html
            - title : Frequently Asked Questions
              submenu :
                - title : FAQ
                  url : faq.html
            - title: Overview
              submenu :
                - title : Overview
                  url : index.html
                - title : Installing Packages
                  url : access.html
                - title : Authoring Packages
                  url : author.html
                - title : Binstar Channels
                  url : channels.html
                - title : Token Generation
                  url : "token_gen.html"
            - title : Conda Packaging
              submenu :
                - title : Authoring Conda Packages
                  url : "conda.html#Authoring"
                - title : Installing Conda Packages
                  url : "conda.html#Installing"
            - title : PyPI Packaging
              submenu :
                - title : Authoring PyPI Packages
                  url : "pypi.html#Authoring"
                - title : Installing PyPI Packages
                  url : "pypi.html#Installing"
            - title: Binstar Build
              submenu :
                - title : Command line client
                  url : "build_cli.html"
                - title : Build Configuration
                  url : "build_config.html"
                - title : Continuous Integration
                  url : "continuous_integration.html"

        enterprise_menu:
            - title: Binstar Onsite
              submenu :
                - title : About
                  url : 'enterprise#install-mongodb'
            - title: Installing
              submenu :
                - title : Install MongoDB
                  url : 'enterprise/install.html#install-mongodb'
            - title: Mirrors
              submenu :
                - title : Mirror pypi.python.org
                  url : enterprise/pypi-mirror.html
            - title: Binstar Client
              submenu :
                - title : Configure the binstar command line client
                  url : enterprise/cli.html


simple_copy:
    - media/js/*
    - media/js/libs*
    - media/css/*
