mode: development # Use "hyde publish -c prod.yaml to have this automatically switch to production
media_root: media # Relative path from content folder.
media_url: /media # URL where the media files are served from.
base_url: /

plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
    - command_line_plugin.CommandLinePlugin

context:
    data:
        repo: https://github.com/binstar/docs.binstar.org
        branch: two-page-layout
        imports: 
          - binstar
        site_title: Binstar Documentation
        author:
            name: Continuum Analytics
            url: "https://binstar.org/"
        home_url: index.html
        brand: Binstar

simple_copy:
    - media/js/*
    - media/js/libs*
    - media/css/*
