menu:
    - title: Getting Started
      url : 'index.html'
    - title : Frequently Asked Questions
      url : 'faq.html'
    - title : Binstar Packages
      url : "packages.html"
    - title : Conda Packaging
      url : "conda.html"
    - title : PyPI Packaging
      url : "pypi.html"
    - title : Token Generation
      url : "token_gen.html"
    - title : Organizations
      url : "organizations.html"
    - title : Channels
      url : "channels.html"