menu:
    - title: Installing Binstar On-Site
      url : 'index.html'
    - title: Trouble Shoot your binstar installation
      url : 'troubleshoot.html'
    - title: Server Maintinance
      url : 'maintenance.html'
    - title: Client Configuration
      url : 'configuration.html'
    - title: Mirroring PyPI
      url : 'pypi-mirror.html'
